# Generated by Django 5.1.4 on 2025-02-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
    ]
